# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'
use_frameworks!
pod 'SimpleAppLibs', '~> 0.1.0'
target 'star' do

end

target 'starTests' do

end

target 'starUITests' do

end
